services:
  - type: web
    name: clickdrop-api
    runtime: node
    rootDir: backend
    buildCommand: pnpm install && pnpm prisma:generate && pnpm build
    startCommand: pnpm prisma:deploy && node dist/main
    plan: free
    region: frankfurt
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: SWAGGER_ENABLED
        value: "true"
      - key: STORAGE_DRIVER
        value: "local"
